### ISSUE TITLE
Статья BAMT+EPDE

### ISSUE THREAD

**Issue by elena-ilinskaya** [ITMO-NSS-team/itmo-nss-team.github.io#11]
Статья по впечатлениям от https://doi.org/10.1098/rspa.2021.0904 по итогу нужно сделать на основе BAMT устойчивое получение диффуров.

- [ ] [Выращивание систем] Михаил Масляев

- [ ] [Совмещение солвера и EPDE] Роман Титов

- [x] [Солвер уравнений + EPDE] Роман Титов

- [ ] [Солвер систем + EPDE] Роман Титов

**Comment by SuperSashka** [comment]
Статья опубликована в журнале Доклады РАН Hvatov A., Titov R. Towards discovery of the differential equations //Doklady Rossijskoj akademii nauk. Matematika, informatika, processy upravleniâ. – 2023. – Т. 514. – №. 2. – С. 109-117.
