### ISSUE TITLE
Обновить разделы с описание алгоритмов для больших БС в статье про BAMT

### ISSUE THREAD

**Issue by Anaxagor** [ITMO-NSS-team/itmo-nss-team.github.io#71]

**Comment by Anaxagor** [comment]
Необходимо обновить все схемы и описание, чтобы не было пересечения с уже опубликованными статьями

**Comment by jrzkaminski** [comment]
Описание отредактировал, рисунки заменил на псевдокод, сократил количество текста

**Comment by Anaxagor** [comment]
Немного вычитать текст, формулировки типа "Our laboratory team has developed" лучше не использовать

**Comment by jrzkaminski** [comment]
> Немного вычитать текст, формулировки типа "Our laboratory team has developed" лучше не использовать

Исправил
