### ISSUE TITLE
Обновить экспериментальные результаты по большим БС в статье про BAMT

### ISSUE THREAD

**Issue by Anaxagor** [ITMO-NSS-team/itmo-nss-team.github.io#73]

**Comment by Anaxagor** [comment]
Надо подумать, как можно обновить эксперименты с большими БС. Возможно провести сравнение с более новыми алгоритмами (например, с алгоритмами непрерывной оптимизации, как NOTEARS).

**Comment by jrzkaminski** [comment]
Глава со сравнением алгоритмов добавлена с картинками

**Comment by Anaxagor** [comment]
Нужно еще показать, как меняется время обучения в зависимости от количества узлов для всех алгоритмов.

**Comment by jrzkaminski** [comment]
> Нужно еще показать, как меняется время обучения в зависимости от количества узлов для всех алгоритмов.

Мы это делали в предыдущих статьях, которые мы цитируем. Но в целом если надо, я могу сделать подобный график, но кажется, что повторимся

**Comment by Anaxagor** [comment]
Ну у нас добавил один алгоритм, плюс обычно если речь идет про алгоритмы для больших графов, обычно всегда требуют подобные графики временной сложности алгоритмов. Также мы обсуждали, что надо посмотреть на пороговые значения, возможно из-за них dagma возвращает пустые графы (кстати как и bigbravebn).

**Comment by Anaxagor** [comment]
В целом, если не добавлять графики времени от количества узлов, но надо хотя бы на гистограммах обозначит количество узлов, может в скобках

**Comment by jrzkaminski** [comment]
> на гистограммах обозначит количество узлов

Сделано
